language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
  - pip install pytest-cov
  - pip install coveralls
script: pytest --cov-report= --cov=mojang_api
after_success: coveralls
