language: python
sudo: false
install: true
script: true
stages:
  - test
  - upload coverage
  - name: deploy
    if: tag IS present
jobs:
  include:
    - stage: test
      python:
        - 3.5
        - 3.6
      install: pip install .
      script: python setup.py test
    - stage: upload coverage
      python: 3.6
      install: pip install coveralls
      script: true
      after_success: coveralls
    - stage: deploy
      python: 3.6
      install: true
      script: true
      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        distributions: sdist bdist_wheel
        skip_cleanup: true
