language: python
python:
  - 3.5
  - 3.6
install:
  - pip install .
script: python setup.py test
after_success:
  - pip install coveralls
  - coveralls
deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    tags: true
