language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
script: pytest --cov-report= --cov=mojang_api
after_success: coveralls
deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    tags: true
